/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ptbcmpplbcmlcsbiixyq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0YmNtcHBsYmNtbGNzYmlpeHlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1NjM0NDEsImV4cCI6MjA4NDEzOTQ0MX0.65Jp-7S9xTidSsPh2kBktGRzIh-Ardi20BWepZw1his"